<?
$MESS["DISK_HELP_1"] = "<strong>A unidade</strong> é a mais recente solução de armazenamento e compartilhamento de arquivo para dinamizar os processos comerciais de sua empresa, disponível na sua conta Bitrix24.";
$MESS["DISK_HELP_2"] = "Gerenciamento de Arquivos e Pastas";
$MESS["DISK_HELP_3"] = "Criação de um Novo Documento";
$MESS["DISK_HELP_4"] = "O que é Bitrix24 Drive?";
$MESS["DISK_HELP_5"] = "Compartilhamento de Documentos";
$MESS["DISK_HELP_6"] = "Rastreamento do Uso de Documentos";
$MESS["DISK_HELP_7"] = "Gerenciamento de Arquivos e Pastas";
$MESS["DISK_HELP_8"] = "O Drive dispõe de uma maneira simples e direta de pesquisar arquivos e pastas, e trabalhar com eles. Você tem duas opções para visualizar e navegar seus documentos. Em primeiro lugar, há uma visualização familiar (em formato de árvore) que organiza seus arquivos de maneira hierárquica. Em segundo lugar, há uma visualização em peças que coloca todos os seus arquivos e pastas numa única página. Qualquer modo que funcione melhor para você, a mudança de um modo para outro é feita com um clique.";
$MESS["DISK_HELP_9"] = "Criação de um Novo Documento";
$MESS["DISK_HELP_10"] = "Há várias maneiras de obter novos documentos em seu Drive. Em primeiro lugar, você pode simplesmente clicar no botão Carregar. Aqueles que preferem arrastar e largar arquivos de uma janela do Explorer também podem certamente fazer isso. Para criar um novo documento na sua conta Bitrix24, clique primeiro em 'Arquivo' e então 'Criar usando', selecionando GoogleDocs, MS Office Web App ou qualquer software office suite instalado na sua empresa (como Microsoft Office, Mac Pages, Open Office, etc.)";
$MESS["DISK_HELP_11"] = "O que é Bitrix24.Drive?";
$MESS["DISK_HELP_12"] = "O Bitrix24.Drive salva seus arquivos tanto em nível local como na nuvem. Uma vez que você salvar um documento, a cópia armazenada na nuvem é automaticamente sincronizada para coincidir com a nova versão. Funciona como mágica: Bitrix24.Drive lhe poupa o aborrecimento de baixar e carregar arquivos. Abra um arquivo, edite e feche - como se você fizesse ao editar um arquivo no seu computador. A última versão do documento estará disponível para você e seus parceiros de trabalho na nuvem, em seus computadores e dispositivos móveis. Apenas baixe o aplicativo para desktop Bitrix24 e conecte seu Bitrix24.Drive para ter acesso às capacidades autosync para vários dispositivos.";
$MESS["DISK_HELP_13"] = "Compartilhamento de Documentos";
$MESS["DISK_HELP_14"] = "Utilize a Fluxo de Atividades para discutir trabalhos e documentos. Comece digitando uma mensagem e anexando um arquivo do Drive. Feito? Clique em \"Enviar\". Seus colegas podem agora visualizar ou editar o documento que você  anexou, se você lhes deu permissão. Toda vez que alguém salva uma nova versão do arquivo, um comentário de notificação é adicionado à sua mensagem original e o arquivo anexo é atualizado. O histórico de modificação do arquivo é mantido; os usuários podem visualizar todas as revisões anteriores feitas do arquivo e reverter para uma versão antiga, se necessário.";
$MESS["DISK_HELP_17"] = "Rastreamento do Uso de Documentos";
$MESS["DISK_HELP_18"] = "Os documentos do Bitrix24 podem ser utilizado em qualquer entidade que permite arquivos anexos (Fluxo de Atividades, Tarefas, Calendário de eventos, CRM). Você pode visualizar as entidades onde o arquivo está sendo usado e quais usuários têm acesso a ele em propriedades do documento (Arquivo > Abrir). Observe que uma vez que exclui um arquivo do seu Drive, você também o exclui de todas as entidades Bitrix24 que ele estava anexado.";
$MESS["DISK_HELP_19"] = "A linha inferior é esta: quando se trata de trabalhar com documentos <strong>Bitrix24.Drive</strong> é a melhor ferramenta, que você sempre pode contar. Saiba mais sobre Drive no curso de treinamento.";
?>