<?
$MESS["DISK_HELP_1"] = "<strong>Drive</strong> es lo último en almacenamiento y soluciones de archivos compartidas disponible dentro de su cuenta Bitrix24, indispensable para agilizar las operaciones de su empresa con sus documentos.";
$MESS["DISK_HELP_2"] = "Gestión de archivos y carpetas";
$MESS["DISK_HELP_3"] = "Creación de un nuevo documento";
$MESS["DISK_HELP_4"] = "¿Qué es Bitrix24 Drive?";
$MESS["DISK_HELP_5"] = "Compartiendo Documentos";
$MESS["DISK_HELP_6"] = "Uso del Seguimiento del documento";
$MESS["DISK_HELP_7"] = "Gestión de archivos y carpetas";
$MESS["DISK_HELP_8"] = "El Drive tiene Características que hacen posible de una manera directa y sencilla el navegar por los archivos y carpetas así como el trabajar con ellos. Usted tiene dos opciones para visualizar y navegar por los documentos. En primer lugar, hay una vista tipo tabla que organiza los archivos de una manera jerárquica. En segundo lugar, está la opción de mosaico que pone a todos los archivos y carpetas en una sola página. Lo que funcione mejor para usted, el paso de un modo a otro se realiza con un solo clic.";
$MESS["DISK_HELP_9"] = "Creando un nuevo documento";
$MESS["DISK_HELP_10"] = "Hay varias maneras de agregar nuevos documentos a su Drive. En primer lugar, puede simplemente hacer clic en el botón Cargar. También puede arrastrar y soltar archivos desde un gestor de archivos como el Explorador. Para crear un nuevo documento desde el interior de su cuenta Bitrix24, haga clic en \"Nuevo documento\" luego \"Crear utilizando ' y seleccione  Google Docs, MS Office Web App, o cualquier suit de software de oficina instalada en su equipo (como Microsoft Office, Mac Pages, Open Office, etc.).";
$MESS["DISK_HELP_11"] = "¿Qué es Bitrix24.Drive?";
$MESS["DISK_HELP_12"] = "Bitrix24.Drive es un sistema completo de almacenamiento, sincronización, edición y participación de archivos. Junto con la aplicación de escritorio, Bitrix24.Drive le permite almacenar archivos tanto en la nube como localmente. Si modifica un documento en su computadora o dispositivo, la copia almacenada en la nube se sincroniza automáticamente para que coincida con la nueva versión. Funciona como magia - Bitrix24.Drive le ahorra la molestia de descargar y cargar archivos. Abra un archivo, edítelo y ciérrelo - al igual que lo haría al editar un archivo en su computador. La última versión del documento estará disponible para usted y sus compañeros de trabajo en la nube, así como en sus ordenadores y dispositivos móviles. Basta con descargar la aplicación de escritorio Bitrix24 y conectar el Bitrix24.Drive para tener acceso a las capacidades AutoSync en múltiples en dispositivos.";
$MESS["DISK_HELP_13"] = "Compartiendo Documentos";
$MESS["DISK_HELP_14"] = "Usted puede utilizar el flujo de actividad para compartir documentos y discutirlos al mismo tiempo. Comience escribiendo un mensaje y adjunte un archivo del Drive. Cuando haya terminado, haga clic en 'Enviar'. Sus colegas pueden ahora ver o editar el documento que adjunto, si usted les dio permiso. Cada vez que alguien guarde una nueva versión del archivo, se agrega un comentario o notificación al mensaje original y el archivo adjunto se actualiza. El historial de modificación del archivo se mantiene, y los usuarios pueden ver todas las revisiones anteriores por hacer para el archivo y volver a una versión anterior, si es necesario.";
$MESS["DISK_HELP_17"] = "Uso del Seguimiento de documentos";
$MESS["DISK_HELP_18"] = "Los documentos dentro Bitrix24 pueden utilizarse en cualquier entidad que permita archivos adjuntos (acciones, tareas, citas del calendario, CRM). Puede ver las entidades en las que se utilizan en el archivo y que los usuarios tengan acceso a la misma en las propiedades del documento (Archivo> Abrir). Observe que una vez que se elimina un archivo desde su Drive, lo elimina de todas las entidades de Bitrix24 y los adjuntos también.";
$MESS["DISK_HELP_19"] = "El planteamiento es el siguiente: cuando se trata de trabajar con documentos, <strong> Bitrix24.Drive </ strong> es su mejor amigo y en el que siempre puede confiar. Lea más sobre Drive, en el curso de capacitación.";
?>