<?
$PERM["extranet"]["11"]="T_15";
$PERM["extranet"]["16"]="T_19";
$PERM["extranet"]["14"]="T_15";
$PERM["extranet"]["13"]="T_15";
$PERM["extranet"]["*"]="D";
$PERM["upload"]["13"]="T_15";
$PERM["upload"]["18"]="T_15";
$PERM["upload"]["*"]="R";
$PERM["pub"]["*"]="R";
$PERM["/"]["2"]="D";
$PERM["/"]["12"]="T_10";
$PERM["/"]["11"]="R";
$PERM["/"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["about"]["8"]="T_9";
$PERM["company"]["8"]="T_9";
?>